import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server/index.js";

export const onRequest = createPagesFunctionHandler({
  build,
  mode: process.env.NODE_ENV,
  getLoadContext: (context) => {
    return {
      cloudflare: {
        // This object matches the return value from Wrangler's
        // `getPlatformProxy` used during development via Remix's
        // `cloudflareDevProxyVitePlugin`:
        // https://developers.cloudflare.com/workers/wrangler/api/#getplatformproxy
        cf: context.request.cf,
        ctx: {
          waitUntil: context.waitUntil.bind(context),
          passThroughOnException: context.passThroughOnException.bind(context),
        },
        caches,
        env: context.env,
      },
    };
  },
});