# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87ea287a9499ad9b411948245394cde0"
name = "Taskly"
application_url = "https://operator-shopify.pages.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,read_products,write_customers,write_discounts,write_fulfillments,write_inventory,write_locations,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [ "https://operator-shopify.pages.dev/api/auth" ]
