name = "taskly"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"

[build.upload]
format = "modules"

[build.upload.esbuild]
external = ["@shopify/polaris/locales/en.json"]