apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskly.fullname" . }}
  labels:
    {{- include "taskly.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taskly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "taskly.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taskly.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.app.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
            - name: HOSTNAME
              value: {{ .Values.app.hostname | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskly.fullname" . }}-secret
                  key: database-url
            - name: SHOPIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskly.fullname" . }}-secret
                  key: shopify-client-id
            - name: SHOPIFY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskly.fullname" . }}-secret
                  key: shopify-client-secret
            - name: SHOPIFY_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "taskly.fullname" . }}-config
                  key: shopify-app-url
            - name: SHOPIFY_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "taskly.fullname" . }}-config
                  key: shopify-scopes
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: ghcr-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}