apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskly.fullname" . }}-secret
  labels:
    {{- include "taskly.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc | quote }}
  shopify-client-id: {{ .Values.shopify.clientId | b64enc | quote }}
  shopify-client-secret: {{ .Values.shopify.clientSecret | b64enc | quote }}