apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskly.fullname" . }}-secret
  labels:
    {{- include "taskly.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc | quote }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  {{- if .Values.oauth.google.clientId }}
  google-client-id: {{ .Values.oauth.google.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.oauth.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.github.clientId }}
  github-client-id: {{ .Values.oauth.github.clientId | b64enc | quote }}
  github-client-secret: {{ .Values.oauth.github.clientSecret | b64enc | quote }}
  {{- end }}